function drawName(x,y) {
    ctx.save();
    ctx.translate(x * UNIT, y * UNIT);
    // ctx.fillRect(x,y,w,h);
    ctx.fillRect(1 * UNIT, 0 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(3 * UNIT, 0 * UNIT, 1 * UNIT, 4 * UNIT);
    ctx.fillRect(1 * UNIT, 4 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(0 * UNIT, 3 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(7 * UNIT, 0 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(6 * UNIT, 1 * UNIT, 1 * UNIT, 4 * UNIT);
    ctx.fillRect(7 * UNIT, 3 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(9 * UNIT, 1 * UNIT, 1 * UNIT, 4 * UNIT);
    ctx.fillRect(12 * UNIT, 0 * UNIT, 1 * UNIT, 5 * UNIT);
    ctx.fillRect(13 * UNIT, 1 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(14 * UNIT, 2 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(15 * UNIT, 1 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(16 * UNIT, 0 * UNIT, 1 * UNIT, 5 * UNIT);
    ctx.fillRect(18 * UNIT, 0 * UNIT, 3 * UNIT, 1 * UNIT);
    ctx.fillRect(19 * UNIT, 1 * UNIT, 1 * UNIT, 3 * UNIT);
    ctx.fillRect(18 * UNIT, 4 * UNIT, 3 * UNIT, 1 * UNIT);
    ctx.fillRect(22 * UNIT, 0 * UNIT, 1 * UNIT, 5 * UNIT);
    ctx.fillRect(23 * UNIT, 0 * UNIT, 3 * UNIT, 1 * UNIT);
    ctx.fillRect(23 * UNIT, 2 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(23 * UNIT, 4 * UNIT, 3 * UNIT, 1 * UNIT);
    ctx.fillRect(0 * UNIT, 7 * UNIT, 1 * UNIT, 5 * UNIT);
    ctx.fillRect(1 * UNIT, 9 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(2 * UNIT, 8 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(3 * UNIT, 7 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(2 * UNIT, 10 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(3 * UNIT, 11 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(6 * UNIT, 7 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(5 * UNIT, 8 * UNIT, 1 * UNIT, 4 * UNIT);
    ctx.fillRect(6 * UNIT, 10 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(8 * UNIT, 8 * UNIT, 1 * UNIT, 4 * UNIT);
    ctx.fillRect(10 * UNIT,7 * UNIT, 1 * UNIT, 5 * UNIT);
    ctx.fillRect(11 * UNIT, 8 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(12 * UNIT, 9 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.fillRect(13 * UNIT, 7 * UNIT, 1 * UNIT, 5 * UNIT);
    ctx.fillRect(16 * UNIT, 7 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(15 * UNIT, 8 * UNIT, 1 * UNIT, 3 * UNIT);
    ctx.fillRect(16 * UNIT, 11 * UNIT, 2 * UNIT, 1 * UNIT);
    ctx.fillRect(18 * UNIT, 9 * UNIT, 1 * UNIT, 2 * UNIT);
    ctx.fillRect(17 * UNIT, 9 * UNIT, 1 * UNIT, 1 * UNIT);
    ctx.restore();
}